### ISSUE TITLE
Realistic HR

### ISSUE THREAD

**Issue by bjbr-dev** [particle-clicker/particle-clicker#101]
I liked the game, but it just seems... unrealistic... that nobel laureates and summer students cost billions or trillions, whilst simultaneously it seems unrealistic that a team of 50 professors can discover the higgs boson.

I propose that you tweak the game such that:
- HR are fixed cost no matter how many you buy (higher levels still cost more) 
    -> This is more realistic, salaries dont increase just because your company hire more
- Add quick add buttons of +100, +1000 etc
- Research cost should be much steeper to keep game balanced
    -> this means that you have to hire 1000s of staff etc to maintain your Hadron Collider and keep getting more research. Its realistic that research requires more data the more indepth you get.

Maybe to stop people spamming lower levels late game, the amount of research each new HR adds is expontenially less. (Doubling the team may only increase research by 1.5x since its less efficient to have more people)

**Comment by Quix0r** [comment]
I like the idea of making things more realistic. But please be aware that this is no CERN simulator where you have expenses and income to manage (balance out). It is "just" an idle-clicker game and shows you some fields of research.

**Comment by kdungs** [comment]
Appreciate the feedback. Please keep in mind that we're not actively maintaining this. It's been almost ten years. As to your comments:

> I liked the game, but it just seems... unrealistic... that nobel laureates and summer students cost billions or trillions, whilst simultaneously it seems unrealistic that a team of 50 professors can discover the higgs boson.

thatsthejoke.gif

> HR are fixed cost no matter how many you buy (higher levels still cost more)
> -> This is more realistic, salaries dont increase just because your company hire more

Yeah nice idea but would require complete re-balancing of the game so... no, sorry.

> Add quick add buttons of +100, +1000 etc

That would actually be nice to have in the scenario you described. But with the exponential costs increases, this is probably not needed, huh? Otherwise, please feel free to send a PR.

> Research cost should be much steeper to keep game balanced
> -> this means that you have to hire 1000s of staff etc to maintain your Hadron Collider and keep getting more research. Its realistic that research requires more data the more indepth you get.
> Maybe to stop people spamming lower levels late game, the amount of research each new HR adds is expontenially less. (Doubling the team may only increase research by 1.5x since its less efficient to have more people)

Again, aintnobodygottimeforthat.mp4, we're not maintaining this and are not going to rebalance the game. Sorry.
