### ISSUE TITLE
CP Violation Upgrade doesnt work

### ISSUE THREAD

**Issue by Confectrician** [particle-clicker/particle-clicker#102]
Within the Game you can upgrade your CP Violation to yield 1M Reputation each Level.
But when you do the Upgrade the reputation there stays on 6.

I have recorded my screen and can share the vid if needed.

Confectrician

**Comment by rhoadeswilliam1** [comment]
I love you guys

**Comment by ValdyrDrengr** [comment]
Still broken...

**Comment by a8ksh4** [comment]
I ran into this too on my desktop.  I swear that when I tried this on my phone yesterday it worked, though.

**Comment by a8ksh4** [comment]
But I'd already upgraded cp violation into the mid 20s maybe when it worked, so possibly the upgrade option is showing up before the other code will activate it based on upgrade level or something.

**Comment by tbaumann** [comment]
Still broken :(

**Comment by kdungs** [comment]
This is amazing! I can't believe there are still people playing this in 2023. We wrote this for fun on just a weekend in 2014. It's been almost ten years. 😆 

I have good news and bad news for you. Actually two pieces of good news.

Firstly, somebody actually submitted a fix for this in 2015: https://github.com/particle-clicker/particle-clicker/commit/fb751fa3768ce0824c4daa7e73c23e9ec33b94b7. So technically speaking (considering the state of this Repo) this issue has been fixed for almost eight years.

Why does it still persist on [cern.ch/particle-clicker](http://cern.ch/particle-clicker) then you ask? Well... We're also not actively maintaining this project anymore. More importantly, none of us are at CERN anymore and I'd be surprised if we could still access the server it's hosted on 🙈 So unfortunately, on [cern.ch/particle-clicker](http://cern.ch/particle-clicker) this will probably never be fixed.

But here's the amazing second piece of good news: In our infinite wisdom we actually built the game as a completely static website in 2014. Back when AngularJS was the hot shit the cool kids were using. What this means in practice is that with literally the click of a button I was able to deploy it to GitHub pages: https://particle-clicker.github.io/particle-clicker/

And it doesn't even stop there. Thanks to the amazing GitHub actions, it'll just always be deployed from the main branch and never be outdated again.

Cheers!

**Comment by ntadej** [comment]
I'm still at CERN 😉

But indeed none of us has time to update the game anymore.

If you want I could rather setup that the CERN hosted webpage is also updated automatically.

**Comment by tbaumann** [comment]
OMG lol that makes me so happy.

I have to admit I don't exactly play the game either. But every time I mention it to someone with a similar kind of humour I get sucked in to a rather lengthy session until I get bored and open the JavaScript console for some mischief.

I shall use the updated link now.

**Comment by ntadej** [comment]
As there seems to be interest I can also update the original link. Just as there was not much activity there was no big reason to.

**Comment by tbaumann** [comment]
> As there seems to be interest I can also update the original link. Just as there was not much activity there was no big reason to.

Depends on what your job is there. If you are a summer student then you are worth your pay and should probably keep clicking the collide button on the accelerator.

**Comment by ntadej** [comment]
I was demoted from that position a long ago unfortunately 😉

**Comment by Confectrician** [comment]
I had to laugh a bit as i read the mail in my inbox telling that this one has ben solved after so many years. :D

Thanks to everyone involved here.
