### ISSUE TITLE
Is the game development officially dead?

### ISSUE THREAD

**Issue by AdmiralAwesome** [particle-clicker/particle-clicker#106]
Hi everyone,

I just wanted to ask about the future development of Particle Clicker - will it be still under development or is it closed forever?

Good job once again!

**Comment by kdungs** [comment]
Dear Marek,

we are no longer actively developing the game. All of the original developers have jobs or academic careers that they are focussing on. Certainly, there are things left to do, so feel free to send PRs.

Cheers,
Kevin
