### ISSUE TITLE
Page source code seems doesn't load perfectly

### ISSUE THREAD

**Issue by ghost** [particle-clicker/particle-clicker#109]
I'm opened Particle Clicker then the interactive element doesn't appear.I already reload the page but it doesn't seems to work. My apologies if I done something wrong, Thank You
![image](https://user-images.githubusercontent.com/61317535/75034924-e0413a00-54e0-11ea-97be-f548e7a62bb2.png)

**Comment by MatthyPlayz** [comment]
Inspect the page and check console, please.

**Comment by Feesh09** [comment]
> Inspect the page and check console, please.

nothing
