### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by luckyjwulf** [particle-clicker/particle-clicker#110]
It is a great clicker/idle game! At about 14 1/2 hours, I had already processed over 25T data and 2.5T funding. But there are a few things left unexplained. What does the JTN stand for in the funding? Also, there should be a system for saving your games to play on multiple devices and settings for things such as scientific notation and visual quality.

**Comment by kdungs** [comment]
Thanks for your suggestions. We're no longer actively working on this. Feel free to send a PR.

Btw. JTN is an inside joke: At CERN, there are coffee machines where you pay with special coins or chips. The french word for those is "jeton". JTN is our shorthand for that.
