### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [particle-clicker/particle-clicker#117]
will you ever update this?

Have a great day!

-Snow

**Comment by kdungs** [comment]
Hey there!

I _just_ set up GitHub pages for Particle Clicker! So this means the latest version will always automatically deploy to https://particle-clicker.github.io/particle-clicker/

For more context on why we can't make it work with the old CERN domain, see https://github.com/particle-clicker/particle-clicker/issues/102#issuecomment-1468816145

**Comment by ntadej** [comment]
We actually can (but let's discuss with Kevin offline 😉)
