### ISSUE TITLE
[Mobile] A complete mobile version

### ISSUE THREAD

**Issue by zhangjiannan** [particle-clicker/particle-clicker#55]
Hey guys @kdungs @ntadej @ibab @gbiro I think the best to migrate this to mobile is to build a mobile app using Ionic, most of the Angular code can be reused, and it works like a proper app on phone!

http://ionicframework.com/

**Comment by kdungs** [comment]
IIRC we made it work on mobile, too. Probably either for Mozfest or after it motivated by the fact that Mozilla handed out free HTML-based phones, LOL.
