### ISSUE TITLE
(UI) Night-Mode

### ISSUE THREAD

**Issue by gabdevue** [particle-clicker/particle-clicker#59]
It's 4a.m. - curse you!! ; ) - I love the game as I did love cookieclicker, which was a bit easier on the eyes at night. A version of particle clicker with a dark background at least for the main screen would be nice - not posed for style reasons. 

This is obviously not an important request, but would be a nice thing to have for those late hours up in bed or during a boring power point presentation...

**Comment by AlexWayfer** [comment]
We still need this.
