### ISSUE TITLE
Lack of instructions / impressions after using Particle Clicker

### ISSUE THREAD

**Issue by RichardPoor** [particle-clicker/particle-clicker#88]
I used your Particle Clicker program and had some issues with it.
First, is the lack of instructions explaining the game to new players.  It does become self explanatory if one has the patience and curiosity to keep going.  However without them it seems easy for people to leave without giving it a real try.
Second, at about JTN 40.0T you purchase what appears to be the last upgrades yet there is still what could be days left to complete all 101 achievements. It takes a long time to earn JTN 146.8T to hire #100 Summer Students.  And an awful lot of clicking to get the 1.8P date needed for level 71 Ξb'- and Ξb*- .  Is it possible to lower the amounts needed for higher level research and HR hires?  As well as stretching out the upgrades so there is some goals there at the later portions of the game?  Maybe have a series of system upgrades to collider components like the ECAL, HCAL, Magnet and other equipment.  It also seemed odd getting a second Noble Prize when I didn't realize that there was one earlier when I was just clicking on upgrades as quick at they popped earlier on.  Why not have some less prestigious awards first like the Copley Medal  or The Wolf Prize and save the Noble for later?  
The last is a minor annoyance at the later stages once you have numbers in the trillions but are only given one decimal place, this makes noticing changes very difficult as they come over several clicks or seconds.  Either adding a second decimal or always showing four significant figures would alleviate this.     

Other than that the game was enjoyable, the information presented was informative, and it kept me busy for a a couple days.

**Comment by sebastianmorel1** [comment]
nice
