### ISSUE TITLE
"Køtbullar" is misspelled

### ISSUE THREAD

**Issue by krixas** [particle-clicker/particle-clicker#89]
The upgrade for the Nobel Laureates including should be called "Köttbullar" and not "Køtbullar". We don't use "ø" in Sweden instead we use the "ö" letter.

**Comment by kdungs** [comment]
Thanks a lot for your feedback. I am sorry for my ignorance of the differences between Swedish and Norvegian. (For me as a German, the ø just looks cooler than the ö ;))
Has been fixed and will be included in the next release.
