### ISSUE TITLE
Extend statistics

### ISSUE THREAD

**Issue by Tampa** [particle-clicker/particle-clicker#99]
I would really like the statistics page to be a bit more clear and contain information about upgrades and the worker performance, since that depends on the order upgrades were applied in.

**Comment by Quix0r** [comment]
Yes. the statistics modal feels very empty.

**Comment by kdungs** [comment]
Feel free to send a PR 😃

**Comment by Tampa** [comment]
I knew research rolls slowly, but holy necroposting batman. I have a slightly changed version that I fiddled around with a bit, but I don't think I can PR this against this version anymore. Nice to see people still work on this though :)

**Comment by kdungs** [comment]
Haha, I'm surprised myself that people still file issues after almost ten years. Best I can do is merge simple PRs once every four years...
